[package]
name = "herodotus_sharp_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json", "multipart"] }
tokio = { version = "1.40.0", features = ["full"] }
clap = { version = "4.0", features = ["derive", "env"] }
serde_json = { version = "1.0.128" }
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-log = "0.1"
cairo-proof-parser = { git = "https://github.com/cartridge-gg/cairo-proof-parser.git", rev = "f175d58" }
starknet-types-core = "~0.1.4"
anyhow = "1.0.89"