[package]
name = "herodotus_sharp_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json", "multipart"] }
tokio = { version = "1.40.0", features = ["full"] }
serde_json = "1.0.101"
clap = { version = "4.0", features = ["derive","env"] }
